import {StyleSheet, Dimensions} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default styles = StyleSheet.create({
  items_container: {
    backgroundColor: 'white',
    flex: 1,
    width: 250,
    height: 400,
  },
  coffee_heading: {
    fontSize: 48,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    // fontFamily: 'sans-serif',
    textAlign: 'left',
    marginVertical: 20,
    marginHorizontal: 10,
    color: '#874d01',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: {width: -1, height: 1},
    textShadowRadius: 2,
    // textShadow: '0 1 0 #000000'
  },
  drinks_container: {
    marginTop: 50,
    flex: 1,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    height: 450,
  },
  drinks: {
    display: 'flex',
    flexDirection: 'row',
    margin: 20,
  },
  linearGradient: {
    borderRadius: 6,
    marginLeft: 10,
    width: windowWidth - 20,
  },
  suggestions_container: {
    marginTop: 50,
    flex: 1,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    height: 450,
  },
  suggestions: {
    display: 'flex',
    flexDirection: 'row',
    margin: 20,
  },
  suggest_heading: {
    fontSize: 48,
    fontWeight: 'bold',
    textAlign: 'left',
    fontFamily: 'Noteworthy-Bold',
    margin: 10,
    color: '#bd7400',
    textShadowColor: '#3d768a',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 0,
  },
  menu_container: {
    display: 'flex',
    flexDirection: 'row',
    marginVertical: 200,
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
  },
  myButton: {
    marginRight: 150,
    marginLeft: 150,
    marginBottom: 60,
    borderRadius: 6,
    backgroundColor: '#82c8e4',
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    width: 250,
    height: 140,
    padding: 10,
  },
  ask_text: {
    color: '#20232a',
    marginBottom: 40,
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
  },
  suggestImage: {
    width: 170,
    height: 150,
    position: 'relative',
    top: -48,
    right: -40,
  },
  drinkImage: {
    width: 300,
    height: 300,
    position: 'relative',
    top: -98,
    right: 24,
  },
  snacksImage: {
    width: 240,
    height: 200,
    position: 'relative',
    top: -88,
    right: -50,
    borderRadius: 5,
    marginBottom: 40,
  },
  image_shadow: {
    shadowColor: 'grey',
    shadowOffset: {height: 6},
    shadowOpacity: 0.9,
  },
  item: {
    fontWeight: 'bold',
    color: '#8e5c00',
    position: 'absolute',
    fontSize: 24,
    fontFamily: 'Noteworthy-Bold',
    margin: 5,
  },
  item_snacks: {
    fontWeight: 'bold',
    color: '#8e5c00',
    position: 'absolute',
    fontSize: 24,
    fontFamily: 'Noteworthy-Bold',
    margin: 50,
  },
  price: {
    position: 'relative',
    marginBottom: 20,
    top: 100,
    color: '#8e5c02',
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
  },
  price_snacks: {
    position: 'relative',
    marginVertical: 50,
    top: 110,
    color: '#8e5c02',
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
  },
  addButton: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    backgroundColor: '#e0e0e0',
    color: '#399bff',
    paddingVertical: 20,
    paddingHorizontal: 40,
    position: 'relative',
    top: 113,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  addButton_snacks: {
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    backgroundColor: '#e0e0e0',
    color: '#399bff',
    paddingVertical: 20,
    paddingHorizontal: 40,
    position: 'relative',
    top: 120,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  plus_minus_buttons: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    top: 150,
    // right: 10,
    position: 'absolute',
  },
  plus_minus_buttons_snacks: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    top: 240,
    // right: 10,
    position: 'absolute',
  },
  plus_minus_minus: {
    paddingHorizontal: 30,
    paddingVertical: 20,
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    backgroundColor: '#e0e0e0',
    color: '#399bff',
    position: 'relative',
    alignItems: 'center',
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  plus_minus_add: {
    paddingHorizontal: 30,
    paddingVertical: 20,
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    backgroundColor: '#e0e0e0',
    color: '#399bff',
    position: 'relative',
    alignItems: 'center',
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  item_details_sg: {
    top: -16,
    fontSize: 15,
    fontFamily: 'Noteworthy-Bold',
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
  },
  item_details: {
    display: 'flex',
    position: 'relative',
    top: -160,
    alignItems: 'center',
  },
  items_container_snacks: {
    flex: 1,
    marginTop: 100,
    fontFamily: 'Noteworthy-Bold',
    fontSize: 40,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    width: 325,
    // height: 370,
    borderRadius: 6,
  },
  snacks_heading: {
    fontSize: 48,
    fontFamily: 'Noteworthy-Bold',
    fontWeight: 'bold',
    textAlign: 'left',
    marginVertical: 20,
    marginHorizontal: 10,
    color: '#874d01',
  },
  snacks_container: {
    marginTop: 50,
    paddingHorizontal: 40,
    // flex: 1,
    flexWrap: 'wrap',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    height: windowHeight - 450,
  },
  snacks: {
    width: 350,
    height: 500,
  },
  footer_container: {
    width: windowWidth,
    height: 80,
    zIndex: 100,
  },
  snacks_linear_container: {
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    // padding: 24,
    width: windowWidth,
    height: windowHeight,
  },
});
