import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  menu_container: {
    marginTop: 120,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    width: 650,
    height: 850,
  },
  myButton: {
    color: 'white',
    textAlign: 'left',
    paddingLeft: 20,
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
  },
  myButton2: {
    position: 'absolute',
    color: 'white',
    textAlign: 'left',
    top: 90,
    left: 20,
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
  },
  myButton3: {
    color: 'white',
    textAlign: 'left',
    paddingLeft: 15,
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
  },

  button1: {
    borderRadius: 30,
    height: 330,
    width: 310,
    position: 'absolute',
    top: 10,
    left: -35,
    marginHorizontal: 30,
    // padding: 10,
    backgroundColor: '#fa824b',
  },
  button2: {
    borderRadius: 30,
    position: 'absolute',
    right: -35,
    marginHorizontal: 30,
    top: 10,
    height: 200,
    width: 310,
    // padding: 10,
    backgroundColor: '#8d96f9',
  },
  button3: {
    borderRadius: 30,
    position: 'absolute',
    top: 350,
    left: -35,
    margin: 30,
    height: 200,
    width: 310,
    // padding: 10,
    backgroundColor: '#358aa9',
  },
  button4: {
    borderRadius: 30,
    height: 330,
    width: 310,
    position: 'absolute',
    top: 220,
    right: -35,
    margin: 30,
    padding: 10,
    backgroundColor: '#fdbc71',
  },
  button5: {
    borderRadius: 30,
    height: 200,
    width: 310,
    position: 'absolute',
    top: 620,
    left: -5,
    // margin:30,
    // padding: 10,
    backgroundColor: '#13233d',
  },
  button6: {
    borderRadius: 30,
    height: 200,
    width: 310,
    position: 'absolute',
    top: 620,
    right: -5,
    // margin:30,
    // padding: 10,
    backgroundColor: '#267bfa',
  },
  container: {
    flex: 1,
    zIndex: -1,
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: '#3348a6'
  },
  menu_images_container: {
    alignItems: 'center',
    width: 200,
    height: 200,
    backgroundColor: 'pink',
    borderRadius: 100,
  },
  menu_images_container1: {
    position: 'relative',
    top: 120,
    left: -30,
    overflow: 'hidden',
    alignItems: 'center',
    width: 210,
    height: 210,
    backgroundColor: '#fbd284',
    borderRadius: 100,
  },
  menu_images_container2: {
    position: 'relative',
    top: 40,
    right: -180,
    // overflow: 'hidden',
    alignItems: 'center',
    width: 150,
    height: 150,
    backgroundColor: '#f9e986',
    borderRadius: 100,
  },
  menu_images_container3: {
    position: 'relative',
    top: 0,
    right: -180,
    // overflow: 'hidden',
    alignItems: 'center',
    width: 150,
    height: 150,
    backgroundColor: '#fbd284',
    borderRadius: 100,
  },
  menu_images_container4: {
    position: 'relative',
    top: 120,
    right: -130,
    // overflow: 'hidden',
    alignItems: 'center',
    width: 200,
    height: 200,
    backgroundColor: '#f08368',
    borderRadius: 100,
  },
  menu_images_container5: {
    position: 'relative',
    top: -30,
    right: -190,
    // overflow: 'hidden',
    alignItems: 'center',
    width: 150,
    height: 150,
    backgroundColor: '#f17ffb',
    borderRadius: 100,
  },
  menu_images_container6: {
    position: 'relative',
    top: -30,
    right: -190,
    // overflow: 'hidden',
    alignItems: 'center',
    width: 150,
    height: 150,
    backgroundColor: '#76f8d5',
    borderRadius: 100,
  },
  ask_images: {
    width: 100,
    height: 100,
  },
  ask_images1: {
    width: 100,
    height: 100,
    marginTop: 10,
  },
  ask_images2: {
    width: 70,
    height: 70,
    marginTop: 30,
  },
  ask_images3: {
    width: 75,
    height: 75,
    marginTop: 20,
  },
  ask_images4: {
    width: 100,
    height: 100,
    marginTop: 40,
  },
  ask_images5: {
    width: 80,
    height: 80,
    marginTop: 40,
    marginRight: 10,
  },

  button_set_1: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  container2: {
    overflow: 'hidden',
    width: 300,
    height: 330,
    borderRadius: 30,
  },
  container3: {
    overflow: 'hidden',
    width: 310,
    height: 200,
    borderRadius: 30,
  },
  container4: {
    overflow: 'hidden',
    width: 300,
    height: 320,
    borderRadius: 30,
  },
  container5: {
    overflow: 'hidden',
    width: 310,
    height: 200,
    borderRadius: 30,
  },
});
