import {StyleSheet, Dimensions} from 'react-native';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default styles = StyleSheet.create({
  container: {
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    width: windowWidth,
    height: windowHeight,
    fontFamily: 'Noteworthy-Bold',
    // backgroundColor: 'white',
  },
  token_modal: {
    marginTop: 300,
    paddingVertical: 8,
    // borderWidth: 4,
    // borderColor: "#286ba6",
    borderRadius: 6,
    // backgroundColor: "#82c8e4",
    color: '#20232a',
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    width: 350,
    height: 240,
    padding: 10,
  },
  myButton: {
    color: 'white',
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
  },
  myButton2: {
    color: 'white',
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    // marginBottom: 70,
    // marginTop: 20
    // alignSelf:'center'
    // textShadowColor: 'rgba(0, 0, 0, 0.75)',
    // textShadowOffset: { width: -1, height: 1 },
    // textShadowRadius: 2
  },
  token_modal2: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth: 4,
    // borderColor: "#20232a",
    borderRadius: 30,
    backgroundColor: 'white',
    // fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    width: 650,
    height: 500,
    position: 'absolute',
    top: windowHeight / 4,
    left: windowWidth / 20,
  },
  modalContent: {
    fontSize: 30,
    marginBottom: 50,
    fontFamily: 'Noteworthy-Bold',
  },
  token_labels_text: {
    fontSize: 40,
    fontWeight: '500',
    fontFamily: 'Noteworthy-Bold',
    marginTop: 10,
    textAlign: 'center',
    position: 'relative',
  },
  token_labels: {
    fontSize: 40,
    fontFamily: 'Noteworthy-Bold',
    width: 400,
    justifyContent: 'center',
  },

  coffee_buttons: {
    marginVertical: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.25,
    shadowRadius: 1,
    elevation: 6,
  },
  type_text: {
    fontSize: 26,
    color: 'white',
    fontWeight: '500',
    fontFamily: 'Noteworthy-Bold',
    // marginTop: 10,
    textAlign: 'center',
    position: 'relative',
  },
  type_button: {
    // borderWidth: 1,
    // margin: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    // borderColor: "#20232a",
    borderRadius: 30,
    // fontSize: 20,
    width: 500,
    height: 60,
    color: 'black',
    // margin: 20,
    backgroundColor: '#43dfe8',
  },
  ok_button_modal: {
    // borderWidth: 1,
    margin: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    // borderColor: "#20232a",
    borderRadius: 30,
    fontSize: 40,
    fontFamily: 'Noteworthy-Bold',
    width: 150,
    height: 70,
    color: 'black',
    // margin: 20,
    backgroundColor: '#00b5ec',
  },
  coffee_button: {
    // borderWidth: 1,
    margin: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    // borderColor: "#20232a",
    borderRadius: 30,
    fontSize: 40,
    fontFamily: 'Noteworthy-Bold',
    width: 250,
    height: 300,
    color: 'black',
    // margin: 20,
    backgroundColor: '#82e33d',
  },
  coffee_button3: {
    // borderWidth: 1,
    margin: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    // borderColor: "#20232a",
    borderRadius: 30,
    fontSize: 40,
    fontFamily: 'Noteworthy-Bold',
    width: 250,
    height: 300,
    color: 'black',
    // margin: 20,
    backgroundColor: '#fc6851',
  },

  coffee_button2: {
    display: 'flex',
    alignItems: 'center',
    fontSize: 40,
    fontFamily: 'Noteworthy-Bold',
    width: 250,
    height: 70,
    color: 'black',
  },
  coffee_button_text: {
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Noteworthy-Bold',
    padding: 5,
    color: 'white',
    // textShadowColor: 'rgba(0, 0, 0, 0.75)',
    // textShadowOffset: { width: -1, height: 1 },
    // textShadowRadius: 2
  },
  coffee_button_text2: {
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Noteworthy-Bold',
    padding: 10,
    color: 'white',
    // textShadowColor: 'rgba(0, 0, 0, 0.75)',
    // textShadowOffset: { width: -1, height: 1 },
    // textShadowRadius: 2
  },
  linear_button: {
    marginTop: 20,
    borderRadius: 6,
    borderWidth: 4,
    borderColor: 'white',
  },
  linear_button2: {
    // marginTop: 20,
    // borderRadius: 6,
    // borderWidth: 4,
    // borderColor: "white",
  },
  micImage: {
    width: 30,
    height: 30,
  },
  opacity: {
    zIndex: 1,
  },
  inputContainer: {
    display: 'flex',
    borderBottomColor: '#F5FCFF',
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    borderBottomWidth: 1,
    width: 450,
    height: 65,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputContainer_voice: {
    display: 'flex',
    borderBottomColor: '#F5FCFF',
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    borderBottomWidth: 1,
    width: 450,
    height: 65,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputContainer_voice2: {
    display: 'flex',
    width: 450,
    // height: 65,
    // marginBottom: 20,
    // flexDirection: 'row',
    alignItems: 'center',
    marginTop: 400,
  },
  input_label: {
    fontSize: 40,
    // marginTop: 300,
    marginBottom: 50,
    fontFamily: 'Noteworthy-Bold',
    fontWeight: 'bold',
    textAlign: 'left',
    color: '#389cff',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: {width: -1, height: 1},
    textShadowRadius: 2,
  },
  inputs: {
    height: 45,
    marginLeft: 16,
    borderBottomColor: '#FFFFFF',
    flex: 1,
  },
  inputs_voice: {
    height: 45,
    marginLeft: 16,
    borderRadius: 30,
    // borderBottomWidth: 1,
    // borderBottomColor: 'black',
    flex: 1,
  },
  inputIcon: {
    width: 30,
    height: 30,
    marginLeft: 15,
    justifyContent: 'center',
  },
  loginButton: {
    backgroundColor: '#00b5ec',
    height: 65,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    width: 450,
    borderRadius: 30,
  },
  loginText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 30,
    fontFamily: 'Noteworthy-Bold',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: {width: -1, height: 1},
    textShadowRadius: 2,
  },
  listening_bg: {
    right: 0,
    backgroundColor: 'black',
    opacity: 0.9,
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    zIndex: 13,
  },
  listening_animation: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 200,
    height: 200,
    resizeMode: 'stretch',
    transform: [{translateX: -100}, {translateY: -50}],
  },
  listening_text: {
    color: 'white',
    // fontSize: 50,
    position: 'absolute',
    top: '30%',
    left: '35%',
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
  },

  listening_animation_mini: {
    marginBottom: 40,
    width: 200,
    height: 200,
  },
  listening_text_mini: {
    color: 'black',
    fontSize: 50,
    top: '-10%',
    textAlign: 'center',
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
  },
  voice_text: {
    marginTop: 100,
    fontSize: 44,
    fontWeight: '800',
    textAlign: 'center',
    fontFamily: 'Noteworthy-Bold',
    color: '#389cff',
    // textShadowColor: 'rgba(0, 0, 0, 0.75)',
    // textShadowOffset: { width: -1, height: 1 },
    // textShadowRadius: 2
  },
  showListeningIcon_container: {
    marginTop: 200,
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    // position: 'absolute',
    // width: windowWidth,
    // height: windowHeight
  },
  token_modal_mini_container: {
    position: 'relative',
    marginTop: 100,
    display: 'flex',
    alignItems: 'center',
  },
  token_modal_mini: {
    marginBottom: 60,
    paddingVertical: 8,
    borderRadius: 6,
    // backgroundColor: "#82c8e4",
    color: '#20232a',
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    width: 370,
    height: 270,
    padding: 10,
  },
  container_mini: {
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  input_heading: {
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    marginTop: 30,
  },
  manual_container: {
    marginTop: 300,
    // shadowColor: "#000",
    // shadowOffset: {
    //     width: 0,
    //     height: 3,
    // },
    // shadowOpacity: 0.27,
    // shadowRadius: 4,
    // elevation: 6,
  },
  input_label: {
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: 'Noteworthy-Bold',
    color: '#389cff',
  },
  buttons: {
    display: 'flex',
    flexDirection: 'row',
  },
  button: {
    // marginHorizontal: 100,
    // marginBottom: 60,
    alignItems: 'center',
    justifyContent: 'center',
    width: 250,
    height: 150,
    borderRadius: 30,
    // borderWidth: 4,
    // borderColor: "white",
    margin: 12,
    backgroundColor: '#ffd23d',
  },
  button2: {
    // marginHorizontal: 100,
    // marginBottom: 60,
    alignItems: 'center',
    justifyContent: 'center',
    width: 250,
    height: 150,
    borderRadius: 30,
    // borderWidth: 4,
    // borderColor: "white",
    margin: 12,
    backgroundColor: '#62dce3',
  },
});
